### PR TITLE
Hide options when nothing is typed.

### PR DESCRIPTION
**Pull request by tehpsalmist**
Hi I’m Ben and I love open source lol

### CODE REVIEW

**Review by dance2die — APPROVED** [review]

**Comment by dance2die** [comment]
@all-contributors please add @tehpsalmist for code

**Comment by dance2die** [comment]
@all-contributors please add @dance2die for design, code, and infra

**Comment by dance2die** [comment]
@all-contributors please add @tehpsalmist for code

**Comment by tehpsalmist** [comment]
Hahaha, yay, finally making my way in OSS!

**Pull request merged**
